'use client';

import { useMemo, useState } from 'react';
import { ArrowUpRight, BriefcaseBusiness, Building2, Check, CheckSquare, CircleAlert, LayoutDashboard, Plus, Save, Search, Settings2, Users, Wallet } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { toast, Toaster } from 'sonner';
import { useCrm } from './use-crm';
import { active, emptyDeal, missing, monthLabel, shiftMonth, shortDate, statuses, today, totals, urgent, validRevenue, yen, type Customer, type Data, type Deal, type Task } from '@/lib/crm/model';

const navigation = [['ダッシュボード', LayoutDashboard], ['案件管理', BriefcaseBusiness], ['顧客管理', Users], ['入金管理', Wallet], ['タスク', CheckSquare]] as const;
const pageHelp: Record<string, string> = {
  ダッシュボード: '案件の動きと、これからの入金をひと目で。', 案件管理: '進捗・書類・売上・入金まで案件単位で管理します。',
  顧客管理: '顧客の連絡先と担当者を管理します。', 入金管理: '入金予定と入金状況を確認します。', タスク: '次の対応を期限順に確認します。',
};

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? 'form-field wide' : 'form-field'}><span>{label}</span>{children}</label>; }
function statusTone(status: Deal['status']) { if (status === '完了') return 'success'; if (['失注', 'キャンセル'].includes(status)) return 'muted-status'; if (['審査中', '契約手続中'].includes(status)) return 'warning'; return 'progress'; }
function Empty({ text }: { text: string }) { return <div className="empty-row">{text}</div>; }

function Dashboard({ data, go }: { data: Data; go: (view: string) => void }) {
  const day = today(), month = day.slice(0, 7);
  const sum = (match: (deal: Deal) => boolean, key: 'net' | 'gross') => data.deals.filter(deal => validRevenue(deal) && match(deal)).reduce((value, deal) => value + totals(deal)[key], 0);
  const needsAttention = data.deals.filter(deal => urgent(deal, day));
  const taskList = data.tasks.filter(task => !task.done).toSorted((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 5);
  return <>
    <div className="metrics">{[
      ['進行案件数', `${data.deals.filter(active).length} 件`, '現在進行中の案件'],
      ['今月総売上', yen(sum(d => d.contractDate.startsWith(month), 'gross')), '契約月をもとに集計'],
      ['今月自社入金予定', yen(sum(d => d.paymentMonth === month, 'net')), monthLabel(month)],
      ['来月自社入金予定', yen(sum(d => d.paymentMonth === shiftMonth(month, 1), 'net')), monthLabel(shiftMonth(month, 1))],
      ['未入金額', yen(sum(d => !d.paid, 'net')), '全期間の未入金合計'],
    ].map(([label, value, note], index) => <section className={`metric metric-${index}`} key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></section>)}</div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>要対応案件 <span className="count">{needsAttention.length}</span></h2><button className="text-button" onClick={() => go('案件管理')}>すべての案件<ArrowUpRight size={16}/></button></div>{needsAttention.length ? needsAttention.slice(0, 5).map(deal => { const customer = data.customers.find(c => c.id === deal.customerId); return <div className="attention-row" key={deal.id}><span className="initial">{customer?.name[0]}</span><div><strong>{customer?.name}</strong><small>{deal.property} {deal.room}</small></div><span className={`badge ${statusTone(deal.status)}`}>{deal.status}</span><div className="action-cell">{deal.action || '次回対応 未設定'}<small className={deal.dueDate && deal.dueDate < day ? 'danger' : ''}>期限 {shortDate(deal.dueDate)}</small></div></div>; }) : <Empty text="要対応の案件はありません"/>}</section>
      <section className="panel"><div className="panel-title"><h2>直近タスク</h2><span className="count">{taskList.length}</span></div>{taskList.length ? taskList.map(task => <div className="task-row" key={task.id}><span className="task-square"/><div>{task.title}<small>{shortDate(task.dueDate)} · {task.owner}</small></div></div>) : <Empty text="未完了のタスクはありません"/>}</section></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>月別入金予定</h2><span className="muted">自社入金額</span></div><div className="bars">{Array.from({ length: 6 }, (_, index) => shiftMonth(month, index - 1)).map(item => { const amount = sum(d => d.paymentMonth === item, 'net'); return <div className="bar-col" key={item}><strong>{yen(amount)}</strong><div className={`bar ${item === month ? 'current' : ''}`} style={{ height: Math.max(4, amount / 1300000 * 150) }}/><span>{Number(item.slice(5))}月</span></div>; })}</div></section>
      <section className="panel"><div className="panel-title"><h2>ステータス別案件</h2><span className="muted">全 {data.deals.length} 件</span></div><div className="status-rows">{['物件提案中', '内見予定', '申込準備', '審査中', '契約手続中', '入居待ち'].map(status => { const count = data.deals.filter(d => d.status === status).length; return <div key={status}><span>{status}</span><div className="status-track"><i style={{ width: `${Math.max(3, count / Math.max(1, data.deals.length) * 100)}%` }}/></div><strong>{count}</strong></div>; })}</div></section></div>
  </>;
}

function Deals({ data, onEdit, onAdd }: { data: Data; onEdit: (deal: Deal) => void; onAdd: () => void }) {
  const [query, setQuery] = useState(''), [status, setStatus] = useState('すべて');
  const rows = data.deals.filter(deal => { const customer = data.customers.find(c => c.id === deal.customerId); return (status === 'すべて' || deal.status === status) && `${customer?.name}${deal.property}${deal.action}`.toLowerCase().includes(query.toLowerCase()); });
  return <section className="list-panel"><div className="toolbar"><div className="search"><Search size={16}/><Input aria-label="案件を検索" value={query} onChange={event => setQuery(event.target.value)} placeholder="顧客名・物件名・次回対応で検索"/></div><NativeSelect value={status} onChange={event => setStatus(event.target.value)} aria-label="ステータスで絞り込み"><option>すべて</option>{statuses.map(item => <option key={item}>{item}</option>)}</NativeSelect><Button onClick={onAdd}><Plus/>案件を登録</Button></div>
    <Table><TableHeader><TableRow><TableHead>顧客 / 物件</TableHead><TableHead>ステータス</TableHead><TableHead>次回対応</TableHead><TableHead>書類</TableHead><TableHead className="money">総売上</TableHead><TableHead className="money">自社入金</TableHead><TableHead>入金月</TableHead></TableRow></TableHeader><TableBody>{rows.map(item => { const customer = data.customers.find(c => c.id === item.customerId), amount = totals(item); return <TableRow key={item.id} onClick={() => onEdit(item)} className="clickable"><TableCell><strong>{customer?.name || '顧客未設定'}</strong><small>{item.property || '物件未設定'} {item.room}</small></TableCell><TableCell><span className={`badge ${statusTone(item.status)}`}>{item.status}</span></TableCell><TableCell>{item.action || '未設定'}<small className={item.dueDate < today() ? 'danger' : ''}>{shortDate(item.dueDate)}</small></TableCell><TableCell>{item.documents.length - missing(item)} / {item.documents.length}</TableCell><TableCell className="money">{yen(amount.gross)}</TableCell><TableCell className="money strong-money">{yen(amount.net)}</TableCell><TableCell>{monthLabel(item.paymentMonth)}</TableCell></TableRow>; })}</TableBody></Table>{!rows.length && <Empty text="条件に一致する案件はありません"/>}</section>;
}

function Customers({ data, onAdd, onEdit }: { data: Data; onAdd: () => void; onEdit: (customer: Customer) => void }) {
  const [query, setQuery] = useState(''); const rows = data.customers.filter(item => `${item.name}${item.phone}${item.email}${item.owner}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="list-panel"><div className="toolbar"><div className="search"><Search size={16}/><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="氏名・連絡先・担当者で検索" aria-label="顧客を検索"/></div><Button onClick={onAdd}><Plus/>顧客を登録</Button></div><Table><TableHeader><TableRow><TableHead>氏名</TableHead><TableHead>電話</TableHead><TableHead>メール</TableHead><TableHead>LINE</TableHead><TableHead>担当者</TableHead><TableHead>案件数</TableHead></TableRow></TableHeader><TableBody>{rows.map(item => <TableRow key={item.id} onClick={() => onEdit(item)} className="clickable"><TableCell><strong>{item.name}</strong></TableCell><TableCell>{item.phone || '—'}</TableCell><TableCell>{item.email || '—'}</TableCell><TableCell>{item.line || '—'}</TableCell><TableCell>{item.owner || '—'}</TableCell><TableCell>{data.deals.filter(deal => deal.customerId === item.id).length} 件</TableCell></TableRow>)}</TableBody></Table></section>;
}

function Payments({ data, toggle }: { data: Data; toggle: (deal: Deal) => void }) {
  return <section className="list-panel"><Table><TableHeader><TableRow><TableHead>入金</TableHead><TableHead>顧客 / 物件</TableHead><TableHead>予定月</TableHead><TableHead>予定日</TableHead><TableHead className="money">総売上</TableHead><TableHead className="money">提携先</TableHead><TableHead className="money">自社入金</TableHead><TableHead>実入金日</TableHead></TableRow></TableHeader><TableBody>{data.deals.filter(validRevenue).toSorted((a, b) => a.paymentDate.localeCompare(b.paymentDate)).map(item => { const customer = data.customers.find(c => c.id === item.customerId), amount = totals(item); return <TableRow key={item.id}><TableCell><button className={`paid-toggle ${item.paid ? 'done' : ''}`} onClick={() => toggle(item)}>{item.paid ? <><Check size={14}/>入金済</> : '未入金'}</button></TableCell><TableCell><strong>{customer?.name}</strong><small>{item.property}</small></TableCell><TableCell>{monthLabel(item.paymentMonth)}</TableCell><TableCell>{item.paymentDate || '未設定'}</TableCell><TableCell className="money">{yen(amount.gross)}</TableCell><TableCell className="money">{yen(amount.partner)}</TableCell><TableCell className="money strong-money">{yen(amount.net)}</TableCell><TableCell>{item.paidDate || '—'}</TableCell></TableRow>; })}</TableBody></Table></section>;
}

function Tasks({ data, update, onAdd }: { data: Data; update: (task: Task) => void; onAdd: () => void }) {
  const rows = data.tasks.toSorted((a, b) => Number(a.done) - Number(b.done) || a.dueDate.localeCompare(b.dueDate));
  return <section className="list-panel"><div className="toolbar"><div className="summary-line"><strong>未完了 {data.tasks.filter(item => !item.done).length} 件</strong><span>完了 {data.tasks.filter(item => item.done).length} 件</span></div><Button onClick={onAdd}><Plus/>タスクを追加</Button></div><div className="task-list">{rows.map(item => { const deal = data.deals.find(d => d.id === item.dealId), customer = data.customers.find(c => c.id === deal?.customerId); return <label className={`task-item ${item.done ? 'is-done' : ''}`} key={item.id}><Checkbox checked={item.done} onCheckedChange={checked => update({ ...item, done: checked === true, version: item.version + 1 })}/><div><strong>{item.title}</strong><small>{customer?.name || '案件未設定'} · {deal?.property || '物件未設定'}</small></div><span className={item.dueDate < today() && !item.done ? 'danger' : ''}>{item.dueDate || '期限未設定'}</span><em>{item.owner || '担当未設定'}</em></label>; })}</div></section>;
}

function CustomerEditor({ customer, open, close, save }: { customer: Customer | null; open: boolean; close: () => void; save: (customer: Customer) => void }) {
  const [draft, setDraft] = useState<Customer | null>(customer); if (customer && draft?.id !== customer.id) setDraft(customer); if (!draft) return null;
  const patch = (key: keyof Customer, value: string) => setDraft({ ...draft, [key]: value });
  return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{draft.version ? '顧客情報を編集' : '顧客を登録'}</DialogTitle><DialogDescription>顧客の連絡先と担当者を入力します。</DialogDescription></DialogHeader><div className="form-grid"><Field label="氏名"><Input value={draft.name} onChange={event => patch('name', event.target.value)}/></Field><Field label="担当者"><Input value={draft.owner} onChange={event => patch('owner', event.target.value)}/></Field><Field label="電話"><Input value={draft.phone} onChange={event => patch('phone', event.target.value)}/></Field><Field label="LINE"><Input value={draft.line} onChange={event => patch('line', event.target.value)}/></Field><Field label="メール" wide><Input type="email" value={draft.email} onChange={event => patch('email', event.target.value)}/></Field><Field label="メモ" wide><Textarea value={draft.note} onChange={event => patch('note', event.target.value)}/></Field></div><DialogFooter><Button variant="outline" onClick={close}>閉じる</Button><Button disabled={!draft.name.trim()} onClick={() => save({ ...draft, version: draft.version + 1 })}><Save/>保存</Button></DialogFooter></DialogContent></Dialog>;
}

function DealEditor({ deal, data, open, close, save }: { deal: Deal | null; data: Data; open: boolean; close: () => void; save: (deal: Deal) => void }) {
  const [draft, setDraft] = useState<Deal | null>(deal), [newDoc, setNewDoc] = useState(''); if (deal && draft?.id !== deal.id) setDraft(deal); if (!draft) return null;
  const patch = <K extends keyof Deal>(key: K, value: Deal[K]) => setDraft({ ...draft, [key]: value }); const amount = totals(draft), customer = data.customers.find(c => c.id === draft.customerId), number = (value: string) => Number(value) || 0;
  return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="deal-dialog"><DialogHeader><DialogTitle>{customer?.name || '新規案件'} <span className={`badge ${statusTone(draft.status)}`}>{draft.status}</span></DialogTitle><DialogDescription>{draft.property || '物件未設定'} {draft.room}</DialogDescription></DialogHeader><div className="deal-summary"><div><span>現在ステータス</span><strong>{draft.status}</strong></div><div><span>次回対応 / 期限</span><strong>{draft.action || '未設定'}</strong><small>{draft.dueDate || '期限未設定'}</small></div><div><span>不足書類</span><strong className={missing(draft) ? 'danger' : ''}>{missing(draft)} 件</strong></div><div><span>総売上</span><strong>{yen(amount.gross)}</strong></div><div><span>提携先支払</span><strong>{yen(amount.partner)}</strong></div><div><span>自社入金</span><strong className="blue">{yen(amount.net)}</strong><small>{monthLabel(draft.paymentMonth)}</small></div></div>
    <Tabs defaultValue="basic"><TabsList variant="line"><TabsTrigger value="basic">基本情報</TabsTrigger><TabsTrigger value="revenue">売上・入金</TabsTrigger><TabsTrigger value="documents">書類</TabsTrigger><TabsTrigger value="schedule">日程・メモ</TabsTrigger></TabsList>
      <TabsContent value="basic"><div className="form-grid"><Field label="顧客"><NativeSelect className="full" value={draft.customerId} onChange={event => patch('customerId', event.target.value)}>{data.customers.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</NativeSelect></Field><Field label="ステータス"><NativeSelect className="full" value={draft.status} onChange={event => patch('status', event.target.value as Deal['status'])}>{statuses.map(item => <option key={item}>{item}</option>)}</NativeSelect></Field><Field label="物件名"><Input value={draft.property} onChange={event => patch('property', event.target.value)}/></Field><Field label="号室"><Input value={draft.room} onChange={event => patch('room', event.target.value)}/></Field><Field label="家賃"><Input type="number" value={draft.rent} onChange={event => patch('rent', number(event.target.value))}/></Field><Field label="共益費"><Input type="number" value={draft.commonFee} onChange={event => patch('commonFee', number(event.target.value))}/></Field><Field label="管理会社" wide><Input value={draft.management} onChange={event => patch('management', event.target.value)}/></Field><Field label="次回対応"><Input value={draft.action} onChange={event => patch('action', event.target.value)}/></Field><Field label="期限"><Input type="date" value={draft.dueDate} onChange={event => patch('dueDate', event.target.value)}/></Field></div></TabsContent>
      <TabsContent value="revenue"><div className="form-grid"><Field label="仲介手数料"><Input type="number" value={draft.brokerage} onChange={event => patch('brokerage', number(event.target.value))}/></Field><Field label="その他報酬"><Input type="number" value={draft.other} onChange={event => patch('other', number(event.target.value))}/></Field><Field label="AD入力方法"><NativeSelect className="full" value={draft.adMode} onChange={event => patch('adMode', event.target.value as Deal['adMode'])}><option value="rate">基準額 × AD率</option><option value="amount">金額を直接入力</option></NativeSelect></Field>{draft.adMode === 'rate' ? <><Field label="AD基準額"><Input type="number" value={draft.adBase} onChange={event => patch('adBase', number(event.target.value))}/></Field><Field label="AD率（%）"><Input type="number" value={draft.adRate} onChange={event => patch('adRate', number(event.target.value))}/></Field></> : <Field label="AD金額"><Input type="number" value={draft.adAmount} onChange={event => patch('adAmount', number(event.target.value))}/></Field>}<Field label="提携先手数料率（%）"><Input type="number" value={draft.partnerRate} onChange={event => patch('partnerRate', number(event.target.value))}/></Field><Field label="入金予定月"><Input type="month" value={draft.paymentMonth} onChange={event => patch('paymentMonth', event.target.value)}/></Field><Field label="入金予定日"><Input type="date" value={draft.paymentDate} onChange={event => { patch('paymentDate', event.target.value); if (event.target.value) patch('paymentMonth', event.target.value.slice(0, 7)); }}/></Field><Field label="実入金日"><Input type="date" value={draft.paidDate} onChange={event => patch('paidDate', event.target.value)}/></Field><label className="check-field"><Checkbox checked={draft.paid} onCheckedChange={value => patch('paid', value === true)}/><span>入金済みにする</span></label></div></TabsContent>
      <TabsContent value="documents"><div className="doc-list">{draft.documents.map(document => <label key={document.id}><Checkbox checked={document.done} onCheckedChange={value => patch('documents', draft.documents.map(item => item.id === document.id ? { ...item, done: value === true } : item))}/><span>{document.name}</span><button onClick={() => patch('documents', draft.documents.filter(item => item.id !== document.id))}>削除</button></label>)}<div className="add-doc"><Input value={newDoc} onChange={event => setNewDoc(event.target.value)} placeholder="必要書類を追加"/><Button variant="outline" disabled={!newDoc.trim()} onClick={() => { patch('documents', [...draft.documents, { id: crypto.randomUUID(), name: newDoc.trim(), done: false }]); setNewDoc(''); }}>追加</Button></div></div></TabsContent>
      <TabsContent value="schedule"><div className="form-grid"><Field label="内見日"><Input type="date" value={draft.viewingDate} onChange={event => patch('viewingDate', event.target.value)}/></Field><Field label="申込日"><Input type="date" value={draft.applicationDate} onChange={event => patch('applicationDate', event.target.value)}/></Field><Field label="契約日"><Input type="date" value={draft.contractDate} onChange={event => patch('contractDate', event.target.value)}/></Field><Field label="入居日"><Input type="date" value={draft.moveInDate} onChange={event => patch('moveInDate', event.target.value)}/></Field><Field label="メモ" wide><Textarea rows={7} value={draft.note} onChange={event => patch('note', event.target.value)}/></Field></div></TabsContent>
    </Tabs><DialogFooter><Button variant="outline" onClick={close}>閉じる</Button><Button onClick={() => save({ ...draft, version: draft.version + 1, history: [...draft.history, { at: new Date().toISOString(), text: '案件情報を更新' }] })}><Save/>保存</Button></DialogFooter></DialogContent></Dialog>;
}

function TaskEditor({ data, open, close, save }: { data: Data; open: boolean; close: () => void; save: (task: Task) => void }) {
  const [draft, setDraft] = useState<Task>({ id: crypto.randomUUID(), version: 0, dealId: data.deals[0]?.id || '', title: '', dueDate: today(), owner: '', done: false });
  return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent><DialogHeader><DialogTitle>タスクを追加</DialogTitle><DialogDescription>案件に紐づけて、担当者と期限を設定します。</DialogDescription></DialogHeader><div className="form-grid one"><Field label="案件"><NativeSelect className="full" value={draft.dealId} onChange={event => setDraft({ ...draft, dealId: event.target.value })}>{data.deals.map(item => <option value={item.id} key={item.id}>{data.customers.find(c => c.id === item.customerId)?.name} / {item.property}</option>)}</NativeSelect></Field><Field label="タスク名"><Input value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })}/></Field><Field label="期限"><Input type="date" value={draft.dueDate} onChange={event => setDraft({ ...draft, dueDate: event.target.value })}/></Field><Field label="担当者"><Input value={draft.owner} onChange={event => setDraft({ ...draft, owner: event.target.value })}/></Field></div><DialogFooter><Button variant="outline" onClick={close}>閉じる</Button><Button disabled={!draft.title.trim()} onClick={() => save({ ...draft, version: 1 })}>追加</Button></DialogFooter></DialogContent></Dialog>;
}

function SettingsEditor({ data, open, close, update }: { data: Data; open: boolean; close: () => void; update: (rate: number) => void }) { const [rate, setRate] = useState(data.settings.partnerRate); return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent><DialogHeader><DialogTitle>基本設定</DialogTitle><DialogDescription>新しく作成する案件の初期値です。既存案件の料率は変わりません。</DialogDescription></DialogHeader><Field label="提携不動産会社への初期手数料率（%）"><Input type="number" min="0" max="100" value={rate} onChange={event => setRate(Number(event.target.value) || 0)}/></Field><DialogFooter><Button variant="outline" onClick={close}>閉じる</Button><Button onClick={() => update(rate)}>保存</Button></DialogFooter></DialogContent></Dialog>; }

export default function CRM() {
  const { data, update, save, saveState } = useCrm(); const [view, setView] = useState('ダッシュボード');
  const [deal, setDeal] = useState<Deal | null>(null), [dealOpen, setDealOpen] = useState(false); const [customer, setCustomer] = useState<Customer | null>(null), [customerOpen, setCustomerOpen] = useState(false); const [taskOpen, setTaskOpen] = useState(false), [settingsOpen, setSettingsOpen] = useState(false);
  const date = useMemo(() => new Date(`${today()}T12:00:00`).toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' }), []);
  const openNewDeal = () => { if (!data.customers.length) return toast.error('先に顧客を登録してください'); setDeal(emptyDeal(data.customers[0].id, data.settings.partnerRate)); setDealOpen(true); };
  const saveDeal = (next: Deal) => { update(current => ({ ...current, deals: current.deals.some(item => item.id === next.id) ? current.deals.map(item => item.id === next.id ? next : item) : [next, ...current.deals] })); setDealOpen(false); toast.success('案件を保存しました'); };
  const newCustomer = (): Customer => ({ id: crypto.randomUUID(), version: 0, name: '', phone: '', email: '', line: '', owner: '', note: '' });
  const saveCustomer = (next: Customer) => { update(current => ({ ...current, customers: current.customers.some(item => item.id === next.id) ? current.customers.map(item => item.id === next.id ? next : item) : [next, ...current.customers] })); setCustomerOpen(false); toast.success('顧客を保存しました'); };
  const content = view === 'ダッシュボード' ? <Dashboard data={data} go={setView}/> : view === '案件管理' ? <Deals data={data} onEdit={item => { setDeal(item); setDealOpen(true); }} onAdd={openNewDeal}/> : view === '顧客管理' ? <Customers data={data} onAdd={() => { setCustomer(newCustomer()); setCustomerOpen(true); }} onEdit={item => { setCustomer(item); setCustomerOpen(true); }}/> : view === '入金管理' ? <Payments data={data} toggle={item => update(current => ({ ...current, deals: current.deals.map(dealItem => dealItem.id === item.id ? { ...dealItem, paid: !dealItem.paid, paidDate: !dealItem.paid ? today() : '', version: dealItem.version + 1 } : dealItem) }))}/> : <Tasks data={data} onAdd={() => setTaskOpen(true)} update={task => update(current => ({ ...current, tasks: current.tasks.map(item => item.id === task.id ? task : item) }))}/>;
  return <SidebarProvider style={{ '--sidebar-width': '230px' } as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span><Building2 size={22}/></span><div>Rental Desk<small>賃貸仲介 CRM</small></div></div></SidebarHeader><SidebarContent><div className="workspace-label">ワークスペース</div><SidebarMenu>{navigation.map(([name, Icon]) => <SidebarMenuItem key={name}><SidebarMenuButton isActive={view === name} onClick={() => setView(name)}><Icon/><span>{name}</span>{name === '案件管理' && <em>{data.deals.length}</em>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><button className="settings-link" onClick={() => setSettingsOpen(true)}><Settings2 size={17}/>設定</button><div className="workspace-person"><span>R</span><div>社内ワークスペース<small>プライベート</small></div></div></SidebarFooter></Sidebar><SidebarInset className="app-main"><header className="topbar"><div><SidebarTrigger/><span>ワークスペース</span><span className="divider">/</span><strong>{view}</strong></div><div className="top-actions"><span>{saveState === '保存中' ? '保存中…' : saveState === '未保存' ? '端末に保存済み' : saveState}</span><Button size="sm" variant="outline" onClick={() => void save()}><Save/>保存</Button><span className="date-label">{date}</span></div></header><main className="page"><div className="page-heading"><div><h1>{view}</h1><p>{pageHelp[view]}</p></div>{view === 'ダッシュボード' && <Button onClick={openNewDeal}><Plus/>案件を登録</Button>}</div><div className="sample-banner"><CircleAlert size={16}/><span>サンプルデータで操作をお試しいただけます。顧客・物件はすべて架空です。</span></div>{content}<p className="footnote">金額は円単位。端数は四捨五入。失注・キャンセル案件は金額集計から除外します。</p></main></SidebarInset><CustomerEditor customer={customer} open={customerOpen} close={() => setCustomerOpen(false)} save={saveCustomer}/><DealEditor deal={deal} data={data} open={dealOpen} close={() => setDealOpen(false)} save={saveDeal}/><TaskEditor key={String(taskOpen)} data={data} open={taskOpen} close={() => setTaskOpen(false)} save={task => { update(current => ({ ...current, tasks: [task, ...current.tasks] })); setTaskOpen(false); toast.success('タスクを追加しました'); }}/><SettingsEditor data={data} open={settingsOpen} close={() => setSettingsOpen(false)} update={rate => { update(current => ({ ...current, settings: { ...current.settings, partnerRate: rate, version: current.settings.version + 1 } })); setSettingsOpen(false); }}/><Toaster richColors position="bottom-right"/></SidebarProvider>;
}
